name: JBStaffTimes
version: '1.0-SNAPSHOT'
main: me.mortaldev.jbstafftimes.Main
api-version: '1.19'
authors: [ MortalDev/Mortality ]
description: A plugin to track the playtime of staff members by week.
